from flask import Blueprint, render_template, request, jsonify, send_file
from io import BytesIO
import logging

barcode_bp = Blueprint('barcode', __name__)
logger = logging.getLogger(__name__)

from app.db import get_db_connection
from app.utils import login_required


@barcode_bp.route('/barcodes')
@login_required
def barcode_page():
    try:
        conn = get_db_connection()
        with conn.cursor() as cursor:
            cursor.execute("SELECT product_id, name, sku FROM product ORDER BY name")
            products = cursor.fetchall()
        conn.close()
        return render_template('barcodes.html', products=products)
    except Exception as e:
        logger.error("Barcode page error: %s", e)
        return render_template('barcodes.html', products=[])


@barcode_bp.route('/api/barcode/generate', methods=['POST'])
@login_required
def generate_barcode():
    data = request.get_json()
    product_id = data.get('product_id')
    barcode_type = data.get('type', 'code128')

    if not product_id:
        return jsonify({'error': 'Product ID required'}), 400

    try:
        conn = get_db_connection()
        with conn.cursor() as cursor:
            cursor.execute("SELECT * FROM product WHERE product_id = %s", (product_id,))
            product = cursor.fetchone()
        conn.close()

        if not product:
            return jsonify({'error': 'Product not found'}), 404

        from barcode.writer import SVGWriter
        import barcode

        code = product.get('sku') or f"PRD-{product['product_id']:05d}"

        if barcode_type == 'code128':
            bc = barcode.get('code128', code, writer=SVGWriter())
        elif barcode_type == 'ean13':
            code = code[:12].ljust(12, '0')
            bc = barcode.get('ean13', code, writer=SVGWriter())
        elif barcode_type == 'qr':
            import qrcode
            qr = qrcode.QRCode(version=1, box_size=10, border=2)
            qr.add_data(code)
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            buf = BytesIO()
            img.save(buf, format='PNG')
            buf.seek(0)
            import base64
            return jsonify({
                'barcode': base64.b64encode(buf.getvalue()).decode(),
                'format': 'png',
                'code': code
            })
        else:
            bc = barcode.get('code128', code, writer=SVGWriter())

        buf = BytesIO()
        bc.write(buf)
        buf.seek(0)
        import base64
        return jsonify({
            'barcode': base64.b64encode(buf.getvalue()).decode(),
            'format': 'svg',
            'code': code
        })
    except Exception as e:
        logger.error("Generate barcode error: %s", e)
        return jsonify({'error': 'Failed to generate barcode'}), 500


@barcode_bp.route('/api/barcode/label/<int:product_id>')
@login_required
def generate_label(product_id):
    try:
        conn = get_db_connection()
        with conn.cursor() as cursor:
            cursor.execute("SELECT * FROM product WHERE product_id = %s", (product_id,))
            product = cursor.fetchone()
        conn.close()

        if not product:
            return "Product not found", 404

        from reportlab.pdfgen import canvas as pdf_canvas
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.lib import colors
        import barcode
        from barcode.writer import SVGWriter

        buffer = BytesIO()
        p = pdf_canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        code = product.get('sku') or f"PRD-{product['product_id']:05d}"
        bc = barcode.get('code128', code, writer=SVGWriter())
        bc_buf = BytesIO()
        bc.write(bc_buf)
        bc_buf.seek(0)

        from reportlab.graphics import renderPDF
        from reportlab.graphics.svglib.svg2rlg import svg2rlg
        drawing = svg2rlg(bc_buf)
        if drawing:
            drawing.width = 150
            drawing.height = 40
            renderPDF.draw(drawing, p, 50, height - 120)

        p.setFont("Helvetica-Bold", 14)
        p.drawString(50, height - 160, product['name'])
        p.setFont("Helvetica", 10)
        p.drawString(50, height - 180, f"SKU: {code}")
        p.drawString(50, height - 195, f"Price: Rs. {float(product['unit_price']):,.2f}")
        p.drawString(50, height - 210, f"Stock: {product['quantity']} units")

        p.setFont("Helvetica-Oblique", 8)
        p.setFillColor(colors.grey)
        p.drawCentredString(width / 2, 40, "Generated by Nexus ERP")

        p.showPage()
        p.save()
        buffer.seek(0)
        return send_file(buffer, as_attachment=True,
                         download_name=f"barcode_{code}.pdf",
                         mimetype='application/pdf')
    except Exception as e:
        logger.error("Generate label error: %s", e)
        return "Error generating label", 500
